# Generated by Django 5.0.6 on 2024-06-20 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cover_image', models.ImageField(upload_to='images/beats/')),
                ('audio_file', models.FileField(upload_to='audio/beats/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_beats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
