# Generated by Django 5.0.6 on 2024-06-23 02:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_alter_beats_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beats',
            name='views',
        ),
        migrations.AddField(
            model_name='beats',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_beats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beats',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 4, 0, 56, 857567)),
        ),
    ]
