# Generated by Django 5.0.6 on 2024-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0017_alter_beats_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beats',
            name='audio_file',
            field=models.FileField(upload_to='audio/beats/'),
        ),
    ]
