# Generated by Django 5.0.6 on 2024-06-22 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_beats_bpm_beats_key_alter_beats_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beats',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='beats',
            name='BPM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beats',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 22, 19, 36, 28, 417156)),
        ),
    ]
