# Generated by Django 5.0.6 on 2024-06-22 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_beats_description_alter_beats_bpm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beats',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 22, 20, 18, 21, 740471)),
        ),
    ]
