# Generated by Django 5.0.6 on 2024-06-23 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0015_beats_score_alter_beats_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beats',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
