# Generated by Django 5.0.6 on 2024-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_beats'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='darkTheme',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Beats',
        ),
    ]
