# Generated by Django 5.0.6 on 2024-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
