# Generated by Django 5.0.6 on 2024-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_pro',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
